SUPABASE_URL = "https://gddseopytaabdxmgubzc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZHNlb3B5dGFhYmR4bWd1YnpjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTExNjk2MSwiZXhwIjoyMDg0NjkyOTYxfQ.8R_j1Zg3JB0_VXViRAzYndYmsHJAIyCZN2v3qwk45-4"

# Remova o [mercadopago] e deixe a chave solta:
MP_ACCESS_TOKEN = "APP_USR-7913434359941227-021020-df970856113428c3f717e569979b5b10-86921969"

# Remova o [strava] e deixe as chaves soltas:
STRAVA_CLIENT_ID = "197487"
STRAVA_CLIENT_SECRET = "2d7e380d8348b5ea2a8e4adf64fdcd69b2ef116f"
STRAVA_REDIRECT_URI = "http://192.168.1.8:8501"
STRAVA_VERIFY_TOKEN = "fabiostrava2026"

# Remova o [twilio] e deixe as chaves soltas:
TWILIO_SID = "ACa4021ac5afa057dcfcfdd0126fbfaa2e"
TWILIO_TOKEN = "a06017e83741c75bab82e7cf5c63b0a2"
TWILIO_PHONE_NUMBER = "14155238886"
MEU_CELULAR = "5511969603611"